image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      mkdir -p ~/.ssh
      cp /workspace/.ssh/id_ed25519 ~/.ssh/id_ed25519 2>/dev/null || true
      cp /workspace/.ssh/id_ed25519.pub ~/.ssh/id_ed25519.pub 2>/dev/null || true
      chmod 600 ~/.ssh/id_ed25519
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_ed25519
      python3 -m venv /workspace/.venv
      source /workspace/.venv/bin/activate
      pip install -r requirements.txt
      pip install psycopg2-binary
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null

  - command: |
      source /workspace/.venv/bin/activate
      . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &

  - command: |
      source /workspace/.venv/bin/activate
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('accountant', 'gretazarazas@gmail.com', 'accountant') if not User.objects.filter(username='admin').exists() else print('Superuser already exists')" | python manage.py shell

vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
