tasks:
  - init: |
      python3 -m venv /workspace/.venv
      source /workspace/.venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install psycopg2-binary
  - command: |
      source /workspace/.venv/bin/activate
      /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: |
      source /workspace/.venv/bin/activate
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('accountant', 'gretazarazas@gmail.com', 'accountant') if not User.objects.filter(username='accountant').exists() else print('Superuser already exists')" | python manage.py shell

