image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      # Ensure SSH keys exist and are copied
      mkdir -p /C:\Users\greta\.vscode\.ssh
      ssh-keygen -t ed25519 -f /C:\Users\greta\.vscode\.ssh/id_ed25519 -N "" 2>/dev/null || true
      cp /C:\Users\greta\.vscode\.ssh/id_ed25519 ~/.ssh/id_ed25519 2>/dev/null || true
      cp /C:\Users\greta\.vscode\.ssh/id_ed25519.pub ~/.ssh/id_ed25519.pub 2>/dev/null || true
      chmod 600 ~/.ssh/id_ed25519
      
      # Configure SSH for GitHub
      echo "Host github.com\n  IdentityFile ~/.ssh/id_ed25519\n  StrictHostKeyChecking no" > ~/.ssh/config
      
      # Start SSH agent and add key
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_ed25519

      # Set up Python virtual environment
      python3 -m venv /C:\Users\greta\.vscode\.venv
      source /C:\Users\greta\.vscode\.venv/bin/activate
      pip install -r requirements.txt
      pip install psycopg2-binary

    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null

  - command: |
      source /C:\Users\greta\.vscode\.venv/bin/activate
      . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &

  - command: |
      source /C:\Users\greta\.vscode\.venv/bin/activate
      python manage.py migrate
      echo "
      from django.contrib.auth import get_user_model;
      User = get_user_model();
      if not User.objects.filter(username='accountant').exists():
          User.objects.create_superuser('accountant', 'gretazarazas@gmail.com', 'accountant')
          print('Superuser created.')
      else:
          print('Superuser already exists.')
      " | python manage.py shell

vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
