# Generated by Django 5.1.6 on 2025-02-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, unique=True)),
                ('coffee_percentage', models.FloatField(default=0.0)),
                ('milkshake_percentage', models.FloatField(default=0.0)),
                ('trailers_count', models.IntegerField(default=0)),
                ('trailers_with_coffee', models.IntegerField(default=0)),
                ('is_bank_holiday', models.BooleanField(default=False)),
                ('has_coffee_machine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3, unique=True)),
            ],
        ),
    ]
