# Generated by Django 5.1.6 on 2025-02-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garysAccApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerselection',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garysAccApp.workday', unique=True),
        ),
    ]
