# Generated by Django 5.1.6 on 2025-02-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garysAccApp', '0002_alter_trailerselection_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerselection',
            name='day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garysAccApp.workday'),
        ),
    ]
