"""
Django settings for garysAccountsProject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# import django_heroku
# import cloudinary
# import cloudinary.uploader
# import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k%ly!lnny(fmia=_d6z@vr2n_d!s)1y=#@&+jg99rnydwd+tu7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ "127.0.0.1", "localhost",
                    '8000-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io',
                    '8001-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io',
                    '8002-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io',
                    '8003-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io',
                    '8006-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io'
                ]

CSRF_TRUSTED_ORIGINS = [
    "https://8000-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io",
    "https://8001-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io",
    "https://8002-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io",
    "https://8003-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io",
    "https://8006-gertazas-garysaccounts-n46yntnbblt.ws-eu118.gitpod.io",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.gitpod.io",  # Allow all Gitpod workspaces
    "https://your-custom-domain.com"  # Add any custom domain you use
]


# Application definition

INSTALLED_APPS = [
    'garysAccApp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'garysAccountsProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'garysAccApp' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'garysAccountsProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# If you also want to serve static files in development, add:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "garysAccApp", "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# cloudinary.config(
#     cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
#     api_key=os.getenv("CLOUDINARY_API_KEY"),
#     api_secret=os.getenv("CLOUDINARY_API_SECRET"),
# )

# # Activate Django-Heroku
# django_heroku.settings(locals())
# Store session data in the database


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Ensure the session cookie is not deleted
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# settings.py
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
